services:

  # client
  go_vue_client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: go-vue-client
    ports:
      - ${FORWARD_CLIENT_PORT}:8080
    tty: true
    command: sh -c "npm run serve"
    volumes:
      - ./client:/usr/src/app

  # Go Server
  go_vue_server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: go-vue-server
    ports:
      - ${FORWARD_SERVER_PORT}:8000
    tty: true
    # command: sh -c "air -c .air.toml"
    volumes:
      - ./server:/go/src/app
    depends_on:
      - 'go_vue_db'

  # db
  go_vue_db:
    image: mariadb:latest
    container_name: go-vue-db
    ports:
      - ${FORWARD_DB_PORT}:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
